/*
 * Copyright (C) 2020 PekinSOFT Systems
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * *****************************************************************************
 * Project    :   Northwind
 * Class      :   CompanyPanel.java
 * Author     :   sean <sean at pekinsoft dot com>
 * Created    :   Dec 20, 2020 @ 10:50:29 AM
 * Modified   :   Dec 20, 2020
 *  
 * Purpose:
 * 	
 * Revision History:
 *  
 * WHEN          BY                  REASON
 * ----------    ------------------- -------------------------------------------
 * Dec 20, 2020    sean             Initial creation.
 * *****************************************************************************
 */
package com.pekinsoft.nwind.options;

import com.pekinsoft.nwind.utils.validation.EmailValidator;
import com.pekinsoft.nwind.utils.validation.PostalCodeValidator;
import java.awt.Color;
import java.awt.SystemColor;
import org.openide.util.NbPreferences;

final class CompanyPanel extends javax.swing.JPanel {

    private final CompanyOptionsPanelController controller;
    private final Color errorColor = new Color(1.0f, 0.714f, 0.757f);
    private final Color warnColor = new Color(0.98f, 0.98f, 0.824f);
    private final Color normalColor = SystemColor.text;
    private boolean isInError;
    private boolean isRequestingFocus;

    CompanyPanel(CompanyOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyPanel = new javax.swing.JPanel();
        companyNameLabel = new javax.swing.JLabel();
        companyNameField = new javax.swing.JTextField();
        streetLabel = new javax.swing.JLabel();
        streetField = new javax.swing.JTextField();
        suiteLabel = new javax.swing.JLabel();
        suiteField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        stateField = new javax.swing.JTextField();
        postalCodeLabel = new javax.swing.JLabel();
        postalCodeField = new javax.swing.JTextField();
        contactLabel = new javax.swing.JLabel();
        contactField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JFormattedTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        ownAuthorityField = new javax.swing.JCheckBox();
        measurementsPanel = new javax.swing.JPanel();
        distanceLabel = new javax.swing.JLabel();
        distanceField = new javax.swing.JComboBox<>();
        fluidLabel = new javax.swing.JLabel();
        fluidField = new javax.swing.JComboBox<>();
        weightLabel = new javax.swing.JLabel();
        weightField = new javax.swing.JComboBox<>();
        tipsLabel = new javax.swing.JLabel();

        companyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.companyPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(companyNameLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.companyNameLabel.text")); // NOI18N

        companyNameField.setText(org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.companyNameField.text")); // NOI18N
        companyNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                companyNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                companyNameFieldFocusLost(evt);
            }
        });
        companyNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(streetLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.streetLabel.text")); // NOI18N

        streetField.setText(org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.streetField.text")); // NOI18N
        streetField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                streetFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                streetFieldFocusLost(evt);
            }
        });
        streetField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(suiteLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.suiteLabel.text")); // NOI18N

        suiteField.setText(org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.suiteField.text")); // NOI18N
        suiteField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                suiteFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                suiteFieldFocusLost(evt);
            }
        });
        suiteField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(cityLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.cityLabel.text")); // NOI18N

        cityField.setText(org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.cityField.text")); // NOI18N
        cityField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityFieldFocusLost(evt);
            }
        });
        cityField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(stateLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.stateLabel.text")); // NOI18N

        stateField.setText(org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.stateField.text")); // NOI18N
        stateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stateFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stateFieldFocusLost(evt);
            }
        });
        stateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(postalCodeLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.postalCodeLabel.text")); // NOI18N

        postalCodeField.setText(org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.postalCodeField.text")); // NOI18N
        postalCodeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                postalCodeFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                postalCodeFieldFocusLost(evt);
            }
        });
        postalCodeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(contactLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.contactLabel.text")); // NOI18N

        contactField.setText(org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.contactField.text")); // NOI18N
        contactField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactFieldFocusLost(evt);
            }
        });
        contactField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(phoneLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.phoneLabel.text")); // NOI18N

        try {
            phoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFieldFocusLost(evt);
            }
        });
        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(emailLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.emailLabel.text")); // NOI18N

        emailField.setText(org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.emailField.text")); // NOI18N
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(ownAuthorityField, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.ownAuthorityField.text")); // NOI18N
        ownAuthorityField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ownAuthorityFieldItemStateChanged(evt);
            }
        });
        ownAuthorityField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ownAuthorityFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout companyPanelLayout = new javax.swing.GroupLayout(companyPanel);
        companyPanel.setLayout(companyPanelLayout);
        companyPanelLayout.setHorizontalGroup(
            companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailLabel)
                    .addComponent(contactLabel)
                    .addComponent(cityLabel)
                    .addComponent(streetLabel)
                    .addComponent(companyNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(companyNameField)
                    .addGroup(companyPanelLayout.createSequentialGroup()
                        .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(companyPanelLayout.createSequentialGroup()
                                .addComponent(streetField)
                                .addGap(18, 18, 18)
                                .addComponent(suiteLabel))
                            .addGroup(companyPanelLayout.createSequentialGroup()
                                .addComponent(cityField)
                                .addGap(18, 18, 18)
                                .addComponent(stateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(postalCodeLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(suiteField)
                            .addComponent(postalCodeField, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
                    .addGroup(companyPanelLayout.createSequentialGroup()
                        .addComponent(contactField)
                        .addGap(18, 18, 18)
                        .addComponent(phoneLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(companyPanelLayout.createSequentialGroup()
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ownAuthorityField)))
                .addContainerGap())
        );
        companyPanelLayout.setVerticalGroup(
            companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyNameLabel)
                    .addComponent(companyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetLabel)
                    .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suiteLabel)
                    .addComponent(suiteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel)
                    .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalCodeLabel))
                .addGap(18, 18, 18)
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailLabel)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ownAuthorityField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        measurementsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.measurementsPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(distanceLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.distanceLabel.text")); // NOI18N

        distanceField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miles", "Kilometers" }));
        distanceField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listSelectedChanged(evt);
            }
        });
        distanceField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                distanceFieldFocusGained(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(fluidLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.fluidLabel.text")); // NOI18N

        fluidField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gallons", "Litres" }));
        fluidField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listSelectedChanged(evt);
            }
        });
        fluidField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fluidFieldFocusGained(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(weightLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.weightLabel.text")); // NOI18N

        weightField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pounds", "Kilograms" }));
        weightField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listSelectedChanged(evt);
            }
        });
        weightField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                weightFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout measurementsPanelLayout = new javax.swing.GroupLayout(measurementsPanel);
        measurementsPanel.setLayout(measurementsPanelLayout);
        measurementsPanelLayout.setHorizontalGroup(
            measurementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(measurementsPanelLayout.createSequentialGroup()
                .addComponent(distanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(distanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fluidLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fluidField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(weightLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        measurementsPanelLayout.setVerticalGroup(
            measurementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(measurementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(distanceLabel)
                .addComponent(distanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(fluidLabel)
                .addComponent(fluidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(weightLabel)
                .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        org.openide.awt.Mnemonics.setLocalizedText(tipsLabel, org.openide.util.NbBundle.getMessage(CompanyPanel.class, "CompanyPanel.tipsLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(companyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(measurementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(companyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(measurementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setTipText(String message) {
        if ( isInError ) {
            tipsLabel.setForeground(Color.red);
        } else {
            tipsLabel.setForeground(SystemColor.textText);
        }
        
        tipsLabel.setText(message);
    }
    
    private void selectText(java.awt.event.FocusEvent evt) {                            
        if ( evt.getSource() instanceof javax.swing.text.JTextComponent ) {
            ((javax.swing.text.JTextComponent)evt.getSource()).selectAll();
        }
    }                           

    private void deselectText(javax.swing.text.JTextComponent field) {
        field.select(0, 0);
    }
    
    private boolean validateWithAuthority() {
        boolean companyInvalid = false;
        boolean streetInvalid = false;
        boolean cityInvalid = false;
        boolean stateInvalid = false;
        boolean postalCodeInvalid = false;
        boolean contactInvalid = false;
        boolean phoneInvalid = false;
        boolean emailInvalid = false;

        String errMsg = "<html>Since your company has its own authority, the"
                + " following fields <strong><em>must</em></strong> have the"
                + " requested data provided:<br><ul>";

        if ( (companyNameField.getText() == null
                || companyNameField.getText().equals("[NOT SET]")
                || companyNameField.getText().isEmpty()) ) {
            errMsg += "<li>Company Name</li>";
            companyNameField.setBackground(errorColor);
            companyInvalid = true;
        } else {
            companyNameField.setBackground(normalColor);
            companyInvalid = false;
        }
        if ( (streetField.getText() == null 
                || streetField.getText().equals("[NOT SET]")
                || streetField.getText().isEmpty()) ) {
            errMsg += "<li>Street Address</li>";
            streetField.setBackground(errorColor);
            streetInvalid = true;
        } else {
            streetField.setBackground(normalColor);
            streetInvalid = false;
        }
        if ( (cityField.getText() == null 
                || cityField.getText().equals("[NOT SET]")
                || cityField.getText().isEmpty()) ) {
            errMsg += "<li>City</li>";
            cityField.setBackground(errorColor);
            cityInvalid = true;
        } else {
            cityField.setBackground(normalColor);
            cityInvalid = false;
        }
        if ( (stateField.getText() == null 
                || stateField.getText().equals("[/]")
                || stateField.getText().isEmpty()) ) {
            errMsg += "<li>State or Province</li>";
            stateField.setBackground(errorColor);
            stateInvalid = true;
        } else {
            stateField.setBackground(normalColor);
            stateInvalid = false;
        }
        if ( (postalCodeField.getText() == null
                || postalCodeField.getText().equals("[NOT SET]")
                || postalCodeField.getText().isEmpty()) ) {
            errMsg += "<li>Postal Code</li>";
            postalCodeField.setBackground(errorColor);
            postalCodeInvalid = true;
        } else {
            postalCodeField.setBackground(normalColor);
            postalCodeInvalid = false;
        }
        if ( (contactField.getText() == null 
                || contactField.getText().equals("[NOT SET]")
                || contactField.getText().isEmpty()) ) {
            errMsg += "<li>Primary Contact</li>";
            contactField.setBackground(errorColor);
            contactInvalid = true;
        } else {
            contactField.setBackground(normalColor);
            contactInvalid = false;
        }
        if ( phoneField.getText().equals("(   )    -    ") ) {
            errMsg += "<li>Phone Number</li>";
            phoneField.setBackground(errorColor);
            phoneInvalid = true;
        } else {
            phoneField.setBackground(normalColor);
            phoneInvalid = false;
        }
        if ( emailField.getText() == null
                || emailField.getText().equals("[NOT SET]")
                || emailField.getText().isEmpty() ) {
            errMsg += "<li>Email Address</li>";
            emailField.setBackground(errorColor);
            emailInvalid = true;
        } else {
            emailField.setBackground(normalColor);
            emailInvalid = false;
        }

        errMsg += "</ul>Please correct these issues in order to save the "
                + "settings.";

        if ( emailInvalid || phoneInvalid || contactInvalid 
                || postalCodeInvalid || stateInvalid || cityInvalid
                || streetInvalid || companyInvalid ) {
            isInError = true;
            setTipText(errMsg);
            companyNameField.requestFocusInWindow();
        } else {
            isInError = false;
            setTipText("");
        }
        
        return emailInvalid && phoneInvalid && contactInvalid 
                && postalCodeInvalid && stateInvalid && cityInvalid
                && streetInvalid && companyInvalid;
    }
    
    private boolean validateWithoutAuthority() {
        if ( companyNameField.getText().equals("[NOT SET]") ) {
            companyNameField.setText("");
            companyNameField.setBackground(warnColor);
        } else if ( companyNameField.getText() == null 
                || companyNameField.getText().isEmpty() ) {
            companyNameField.setBackground(warnColor);
        }
        if ( streetField.getText().equals("[NOT SET]") ) {
            streetField.setText("");
            streetField.setBackground(warnColor);
        } else if ( streetField.getText() == null
                || streetField.getText().isEmpty() ) {
            streetField.setBackground(warnColor);
        }
        if ( cityField.getText().equals("[NOT SET]") ) {
            cityField.setText("");
            cityField.setBackground(warnColor);
        } else if ( cityField.getText() == null
                || cityField.getText().isEmpty() ) {
            cityField.setBackground(warnColor);
        }
        if ( stateField.getText().equals("[/]") ) {
            stateField.setText("");
            stateField.setBackground(warnColor);
        } else if ( stateField.getText() == null
                || stateField.getText().isEmpty() ) {
            stateField.setBackground(warnColor);
        }
        if ( postalCodeField.getText().equals("[NOT SET]") ) {
            postalCodeField.setText("");
            postalCodeField.setBackground(warnColor);
        } else if ( postalCodeField.getText() == null 
                || postalCodeField.getText().isEmpty() ) {
            postalCodeField.setBackground(warnColor);
        } 
        if ( contactField.getText().equals("[NOT SET]") ) {
            contactField.setText("");
            contactField.setBackground(warnColor);
        } else if ( contactField.getText() == null
                || contactField.getText().isEmpty() ) {
            contactField.setBackground(warnColor);
        }
        if ( emailField.getText().equals("[NOT SET]") ) {
            emailField.setText("");
            emailField.setBackground(warnColor);
        } else if ( emailField.getText() == null
                || emailField.getText().isEmpty() ) {
            emailField.setBackground(warnColor);
        }
        if ( phoneField.getText().equals("(   )    -    ") ) {
            phoneField.setBackground(warnColor);
        }
        
        // No data is required if the own authority field is not checked.
        return true;
    }
    
    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        deselectText(emailField);
        
        // Validate the email address:
        if ( emailField.getText() != null
                && !emailField.getText().isEmpty()
                && !emailField.getText().equals("[NOT SET]") ) {
            if ( emailField.getText() != null 
                    && (!emailField.getText().isEmpty()
                    && !emailField.getText().equals("[NOT SET]")) ) {
                if ( !EmailValidator.isValid(emailField.getText()) ) {
                    emailField.setBackground(errorColor);
                    isInError = true;
                    setTipText("<html>The email that you entered is not a valid "
                            + "email address.<br><br><em>Please check the spelling and "
                            + "correct the email address.</em>");
                    if ( !isRequestingFocus ) {
                        isRequestingFocus = true;
                        emailField.requestFocusInWindow();
                    }
                } else {
                    emailField.setBackground(normalColor);
                    isInError = false;
                    isRequestingFocus = false;
                }
            }
        }
        
        if ( !ownAuthorityField.isSelected() && emailField.getText() != null
                && !emailField.getText().isEmpty()
                && !emailField.getText().equals("[NOT SET]")
                && EmailValidator.isValid(emailField.getText()) ) {
            emailField.setBackground(normalColor);
        } else if ( ownAuthorityField.isSelected() 
                && (emailField.getText() == null
                || emailField.getText().isEmpty()
                || emailField.getText().equals("[NOT SET]")) ) {
            emailField.setText("");
            emailField.setBackground(errorColor);
        } else {
            if ( !emailField.getText().isEmpty() ) {
                emailField.setText("");
                emailField.setBackground(warnColor);
            }
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        selectText(evt);
        
        if ( !isInError ) {
            setTipText("<html>Enter the email address for either:"
                    + "<ul><li>The contact listed as the <em>Primary Contact</em></li>"
                    + "<li>The primary email address for the company</li></ul>");
        } else {
            setTipText(tipsLabel.getText());
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void companyNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameFieldFocusGained
        selectText(evt);
        
        if ( !isInError ) {
            setTipText("<html>Enter your company's name in this field.<br><br>"
                    + "Northwind Traders uses this information in various ways,"
                    + " especially if your company has its own authority and "
                    + "sends invoices for payment.");
        } else {
            setTipText(tipsLabel.getText());
        }
    }//GEN-LAST:event_companyNameFieldFocusGained

    private void companyNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameFieldFocusLost
        deselectText(companyNameField);
        
        // To validate, we need to see if the own authority checkbox is checked.
        if ( ownAuthorityField.isSelected() ) {
            if ( companyNameField.getText().equals("[NOT SET]")
                    || companyNameField.getText() == null 
                    || companyNameField.getText().isEmpty() ) {
                isInError = true;
                companyNameField.setBackground(errorColor);
                setTipText("<html>Since your company has its own authority, "
                        + "the Company Name is a required field and must have "
                        + "your company's name entered.");
                if ( !isRequestingFocus ) {
                    isRequestingFocus = true;
                    companyNameField.requestFocusInWindow();
                }
            } else {
                isInError = false;
                companyNameField.setBackground(normalColor);
                isRequestingFocus = false;
            }
        } else {
            if ( companyNameField.getText() == null
                    || companyNameField.getText().isEmpty()
                    || companyNameField.getText().equals("[NOT SET]") ) {
                companyNameField.setText("");
                companyNameField.setBackground(warnColor);
            } else {
                companyNameField.setBackground(normalColor);
            }
        }
    }//GEN-LAST:event_companyNameFieldFocusLost

    private void streetFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetFieldFocusGained
        selectText(evt);
        
        if ( !isInError ) {
            setTipText("<html>Enter your company's street address in this field."
                    + "<br><br>Northwind Traders uses this information in "
                    + "various ways, especially if your company has its own "
                    + "authority and sends invoices for payment.");
        } else {
            setTipText(tipsLabel.getText());
        }
    }//GEN-LAST:event_streetFieldFocusGained

    private void streetFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetFieldFocusLost
        deselectText(streetField);
        
        // To validate, we need to see if the own authority checkbox is checked.
        if ( ownAuthorityField.isSelected() ) {
            if ( streetField.getText().equals("[NOT SET]")
                    || streetField.getText() == null 
                    || streetField.getText().isEmpty() ) {
                isInError = true;
                streetField.setBackground(errorColor);
                setTipText("<html>Since your company has its own authority, "
                        + "the Street is a required field and must have "
                        + "your company's mailing street address entered.");
                if ( !isRequestingFocus ) {
                    isRequestingFocus = true;
                    streetField.requestFocusInWindow();
                }
            } else {
                isInError = false;
                streetField.setBackground(normalColor);
                isRequestingFocus = false;
            }
        } else {
            if ( streetField.getText() == null
                    || streetField.getText().isEmpty()
                    || streetField.getText().equals("[NOT SET]") ) {
                streetField.setText("");
                streetField.setBackground(warnColor);
            } else {
                streetField.setBackground(normalColor);
            }
        }
    }//GEN-LAST:event_streetFieldFocusLost

    private void suiteFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_suiteFieldFocusGained
        selectText(evt);
        
        if ( !isInError ) {
            setTipText("<html>Enter your company's suite number or PO Box "
                    + "number, if any.<br><br>Since not all companies have "
                    + "a suite or PO Box number, this field is not required.");
        } else {
            setTipText(tipsLabel.getText());
        }
    }//GEN-LAST:event_suiteFieldFocusGained

    private void suiteFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_suiteFieldFocusLost
        deselectText(suiteField);
        
        // The suite field is not required, because not all companies have a 
        //+ suite or PO Box number associated with their address. However, we do
        //+ not want to leave this field with the value of "[NOT SET]" and we do
        //+ want to provide an indicator that there is no value provided. 
        //+ Therefore, we will "validate" this field as follows:
        //+
        //+     * If the value remains "[NOT SET]", we will delete it.
        //+     * If there is not value provided, we will change the background
        //+       color to our warning color (LightGoldenRodYellow[#FAFAD2]).
        if ( suiteField.getText().equals("[NOT SET]") ) {
            suiteField.setText("");
        }
        
        if ( suiteField.getText() == null || suiteField.getText().isEmpty() ) {
            suiteField.setBackground(warnColor);
        } else {
            suiteField.setBackground(normalColor);
        }
    }//GEN-LAST:event_suiteFieldFocusLost

    private void cityFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFieldFocusGained
        selectText(evt);
        
        if ( !isInError ) {
            setTipText("<html>Entery your company's city name.<br><br>"
                    + "Northwind Traders uses this information in various ways,"
                    + " especially if your company has its own authority and "
                    + "needs to send invoices for payment.");
        } else {
            setTipText(tipsLabel.getText());
        }
    }//GEN-LAST:event_cityFieldFocusGained

    private void cityFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFieldFocusLost
        deselectText(cityField);
        
        // To validate, we need to see if the own authority checkbox is checked.
        if ( ownAuthorityField.isSelected() ) {
            if ( cityField.getText().equals("[NOT SET]")
                    || cityField.getText() == null 
                    || cityField.getText().isEmpty() ) {
                isInError = true;
                cityField.setBackground(errorColor);
                setTipText("<html>Since your company has its own authority, "
                        + "the City is a required field and must have "
                        + "your company's city location entered.");
                if ( !isRequestingFocus ) {
                    isRequestingFocus = true;
                    cityField.requestFocusInWindow();
                }
            } else {
                isInError = false;
                isRequestingFocus = false;
                cityField.setBackground(normalColor);
            }
        } else {
            if ( cityField.getText() == null
                    || cityField.getText().isEmpty()
                    || cityField.getText().equals("[NOT SET]") ) {
                cityField.setText("");
                cityField.setBackground(warnColor);
            } else {
                cityField.setBackground(normalColor);
            }
        }
    }//GEN-LAST:event_cityFieldFocusLost

    private void stateFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateFieldFocusGained
        selectText(evt);
        
        if ( !isInError ) {
            setTipText("<html>Enter your company's State or Province.<br><br>"
                    + "Northwind Traders uses this information in various ways,"
                    + " especially if your company has its own authority and "
                    + "sends invoices for payment.");
        } else {
            setTipText(tipsLabel.getText());
        }
    }//GEN-LAST:event_stateFieldFocusGained

    private void stateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateFieldFocusLost
        deselectText(stateField);
        
        // To validate, we need to see if the own authority checkbox is checked.
        if ( ownAuthorityField.isSelected() ) {
            if ( stateField.getText().equals("[NOT SET]")
                    || stateField.getText() == null 
                    || stateField.getText().isEmpty() ) {
                isInError = true;
                stateField.setBackground(errorColor);
                setTipText("<html>Since your company has its own authority, "
                        + "the State is a required field and must have "
                        + "your company's State or Province entered.");
                if ( !isRequestingFocus ) {
                    isRequestingFocus = true;
                    stateField.requestFocusInWindow();
                }
            } else {
                isInError = false;
                stateField.setBackground(normalColor);
                isRequestingFocus = false;
            }
        } else {
            if ( stateField.getText() == null 
                    || stateField.getText().isEmpty()
                    || stateField.getText().equals("[/]") ) {
                stateField.setText("");
                stateField.setBackground(warnColor);
            } else {
                stateField.setBackground(normalColor);
            }
        }
    }//GEN-LAST:event_stateFieldFocusLost

    private void postalCodeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postalCodeFieldFocusGained
        selectText(evt);
        
        if ( !isInError ) {
            setTipText("<html>Enter your company's Postal Code.<br><br>"
                    + "Northwind Traders uses this information in various ways,"
                    + " especially if your company has its own authority and "
                    + "sends invoices for payment.");
        } else {
            setTipText(tipsLabel.getText());
        }
    }//GEN-LAST:event_postalCodeFieldFocusGained

    private void postalCodeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postalCodeFieldFocusLost
        deselectText(postalCodeField);
        
        // Validate the Postal Code:
        if ( ownAuthorityField.isSelected() ) {
            if ( postalCodeField.getText() != null
                    && (!postalCodeField.getText().isEmpty() 
                    && !postalCodeField.getText().equals("[NOT SET]")) ) {
                if ( !PostalCodeValidator.isValid(postalCodeField.getText()) ) {
                    postalCodeField.setBackground(errorColor);
                    isInError = true;
                    setTipText("<html>The email that you entered is not a valid "
                            + "email address.<br><br><em>Please check the spelling and "
                            + "correct the email address.</em>");
                    if ( !isRequestingFocus ) {
                        isRequestingFocus = true;
                        postalCodeField.requestFocusInWindow();
                    }
                } else {
                    postalCodeField.setBackground(normalColor);
                    isInError = false;
                    isRequestingFocus = false;
                }
            }
        } else {
            if ( postalCodeField.getText() == null
                    || postalCodeField.getText().isEmpty()
                    || postalCodeField.getText().equals("[NOT SET]") ) {
                postalCodeField.setText("");
                postalCodeField.setBackground(warnColor);
            } else {
                if ( !PostalCodeValidator.isValid(postalCodeField.getText()) ) {
                    postalCodeField.setBackground(errorColor);
                    isInError = true;
                    setTipText("<html>The email that you entered is not a valid "
                            + "email address.<br><br><em>Please check the spelling and "
                            + "correct the email address.</em>");
                    if ( !isRequestingFocus ) {
                        isRequestingFocus = true;
                        postalCodeField.requestFocusInWindow();
                    }
                } else {
                    postalCodeField.setBackground(normalColor);
                    isInError = false;
                    isRequestingFocus = false;
                }
            }
        }
    }//GEN-LAST:event_postalCodeFieldFocusLost

    private void contactFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactFieldFocusGained
        selectText(evt);
        
        if ( !isInError ) {
            setTipText("<html>Enter the primary contact for your company.<br>"
                    + "<br>Northwind Traders uses this information in various "
                    + "ways, especially if your company has its own authority "
                    + "and has customers contacting the company.");
        } else {
            setTipText(tipsLabel.getText());
        }
    }//GEN-LAST:event_contactFieldFocusGained

    private void contactFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactFieldFocusLost
        deselectText(contactField);
        
        // To validate, we need to see if the own authority checkbox is checked.
        if ( ownAuthorityField.isSelected() ) {
            if ( contactField.getText().equals("[NOT SET]")
                    || contactField.getText() == null 
                    || contactField.getText().isEmpty() ) {
                isInError = true;
                contactField.setBackground(errorColor);
                setTipText("<html>Since your company has its own authority, "
                        + "the Primary Contact is a required field and must have "
                        + "your company's primary point of contact's name "
                        + "entered.");
                if ( !isRequestingFocus ) {
                    isRequestingFocus = true;
                    contactField.requestFocusInWindow();
                }
            } else {
                isInError = false;
                contactField.setBackground(normalColor);
                isRequestingFocus = false;
            }
        } else {
            if ( contactField.getText() == null
                    || contactField.getText().isEmpty()
                    || contactField.getText().equals("[NOT SET]") ) {
                contactField.setText("");
                contactField.setBackground(warnColor);
            } else {
                contactField.setBackground(normalColor);
            }
        }
    }//GEN-LAST:event_contactFieldFocusLost

    private void phoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFieldFocusGained
        selectText(evt);
        
        if ( !isInError ) {
            setTipText("<html>Enter your company's phone number.<br><br>"
                    + "Northwind Traders uses this information in various ways,"
                    + " especially if your company has its own authority and "
                    + "sends invoices for payment.");
        } else {
            setTipText(tipsLabel.getText());
        }
    }//GEN-LAST:event_phoneFieldFocusGained

    private void phoneFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFieldFocusLost
        deselectText(phoneField);
        
        // To validate, we need to see if the own authority checkbox is checked.
        if ( ownAuthorityField.isSelected() ) {
            if ( phoneField.getText().equals("[NOT SET]")
                    || phoneField.getText() == null 
                    || phoneField.getText().isEmpty() ) {
                isInError = true;
                phoneField.setBackground(errorColor);
                setTipText("<html>Since your company has its own authority, "
                        + "Phone is a required field and must have "
                        + "your company's primary phone number entered.");
                if ( !isRequestingFocus ) {
                    isRequestingFocus = true;
                    phoneField.requestFocusInWindow();
                }
            } else {
                isInError = false;
                phoneField.setBackground(normalColor);
                isRequestingFocus = false;
            }
        } else {
            if ( phoneField.getText().equals("(   )    -    ") ) {
                phoneField.setBackground(warnColor);
            } else {
                phoneField.setBackground(normalColor);
            }
        }
    }//GEN-LAST:event_phoneFieldFocusLost

    private void ownAuthorityFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ownAuthorityFieldFocusGained
        if ( !isInError ) {
            setTipText("<html>If your company has its own authority, select "
                    + "this field.<br><br>If your company is leased to a motor "
                    + "carrier, then leave this field unselected.");
        }
    }//GEN-LAST:event_ownAuthorityFieldFocusGained

    private void ownAuthorityFieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ownAuthorityFieldItemStateChanged
        // Validate the other data on this panel:
        if ( ownAuthorityField.isSelected() ) {
            validateWithAuthority();
        } else {
            validateWithoutAuthority();
        }
        
        controller.changed();
    }//GEN-LAST:event_ownAuthorityFieldItemStateChanged

    private void dataChanged(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataChanged
        controller.changed();
    }//GEN-LAST:event_dataChanged

    private void listSelectedChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listSelectedChanged
        controller.changed();
    }//GEN-LAST:event_listSelectedChanged

    private void distanceFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_distanceFieldFocusGained
        setTipText("<html>Choose between standard and metric distance "
                + "measurements.<ul><li>Miles</li><li>Kilometers</li></ul>");
    }//GEN-LAST:event_distanceFieldFocusGained

    private void fluidFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fluidFieldFocusGained
        setTipText("<html>Choose between standard and metric liquid "
                + "measurements.<ul><li>Gallons</li><li>Litres</li></ul>");
    }//GEN-LAST:event_fluidFieldFocusGained

    private void weightFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weightFieldFocusGained
        setTipText("<html>Choose between standard and metric weight "
                + "measurements.<ul><li>Pounds</li><li>Kilograms</li></ul>");
    }//GEN-LAST:event_weightFieldFocusGained
    
    void load() {
        // Read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(CompanyPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(CompanyPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
        companyNameField.setText(NbPreferences.root().get("company.name", "[NOT SET]"));
        streetField.setText(NbPreferences.root().get("company.street", "[NOT SET]"));
        suiteField.setText(NbPreferences.root().get("company.suite", "[NOT SET]"));
        cityField.setText(NbPreferences.root().get("company.city", "[NOT SET]"));
        stateField.setText(NbPreferences.root().get("company.state", "[/]"));
        postalCodeField.setText(NbPreferences.root().get("company.postalCode", "[NOT SET]"));
        contactField.setText(NbPreferences.root().get("company.contact", "[NOT SET]"));
        phoneField.setText(NbPreferences.root().get("company.phone", ""));
        emailField.setText(NbPreferences.root().get("company.email", "[NOT SET]"));
        ownAuthorityField.setSelected(NbPreferences.root().getBoolean("company.authority", false));
        distanceField.setSelectedItem(NbPreferences.root().get("default.distance", "Miles"));
        fluidField.setSelectedItem(NbPreferences.root().get("default.fluid", "Gallons"));
        weightField.setSelectedItem(NbPreferences.root().get("default.weight", "Pounds"));
        
        for ( java.awt.Component c : this.getComponents() ) {
            if ( c instanceof javax.swing.text.JTextComponent ) {
                if ( ((javax.swing.text.JTextComponent)c).getText() == null
                        || ((javax.swing.text.JTextComponent)c).getText().isEmpty() 
                        || ((javax.swing.text.JTextComponent)c).getText().equals("(   )    -    ") ) {
                    if ( !ownAuthorityField.isSelected() ) {
                        ((javax.swing.text.JTextComponent)c).setBackground(warnColor);
                    } else {
                        ((javax.swing.text.JTextComponent)c).setBackground(errorColor);
                    }
                }
            }
        }
    }

    void store() {
        // Store modified settings
        // Example:
        // Preferences.userNodeForPackage(CompanyPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(CompanyPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
        NbPreferences.root().put("company.name", companyNameField.getText());
        NbPreferences.root().put("company.street", streetField.getText());
        NbPreferences.root().put("company.suite", suiteField.getText());
        NbPreferences.root().put("company.city", cityField.getText());
        NbPreferences.root().put("company.state", stateField.getText());
        NbPreferences.root().put("company.postalCode", postalCodeField.getText());
        NbPreferences.root().put("company.contact", contactField.getText());
        NbPreferences.root().put("company.phone", phoneField.getText());
        NbPreferences.root().put("company.email", emailField.getText());
        NbPreferences.root().putBoolean("company.authority", ownAuthorityField.isSelected());
        NbPreferences.root().put("default.distance", distanceField.getSelectedItem().toString());
        NbPreferences.root().put("default.fluid", fluidField.getSelectedItem().toString());
        NbPreferences.root().put("default.weight", weightField.getSelectedItem().toString());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        if ( ownAuthorityField.isSelected() ) {
            return validateWithAuthority();
        } else {
            return validateWithoutAuthority();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JPanel companyPanel;
    private javax.swing.JTextField contactField;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JComboBox<String> distanceField;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JComboBox<String> fluidField;
    private javax.swing.JLabel fluidLabel;
    private javax.swing.JPanel measurementsPanel;
    private javax.swing.JCheckBox ownAuthorityField;
    private javax.swing.JFormattedTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField postalCodeField;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JTextField stateField;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField streetField;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField suiteField;
    private javax.swing.JLabel suiteLabel;
    private javax.swing.JLabel tipsLabel;
    private javax.swing.JComboBox<String> weightField;
    private javax.swing.JLabel weightLabel;
    // End of variables declaration//GEN-END:variables
}
