/*
 * Copyright (C) 2020 PekinSOFT Systems
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * *****************************************************************************
 * Project    :   Northwind
 * Class      :   TruckPanel.java
 * Author     :   sean <sean at pekinsoft dot com>
 * Created    :   Dec 12, 2020 @ 1:00:44 PM
 * Modified   :   Dec 12, 2020
 *  
 * Purpose:
 * 	
 * Revision History:
 *  
 * WHEN          BY                  REASON
 * ----------    ------------------- -------------------------------------------
 * Dec 12, 2020    sean             Initial creation.
 * *****************************************************************************
 */
package com.pekinsoft.nwind.options;

import com.pekinsoft.nwind.utils.NotifyUtil;
import java.awt.Color;
import java.awt.SystemColor;
import java.text.SimpleDateFormat;
import java.util.Date;

final class TruckPanel extends javax.swing.JPanel {

    private final TruckOptionsPanelController controller;

    TruckPanel(TruckOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionsLabel = new javax.swing.JLabel();
        truckPanel = new javax.swing.JPanel();
        truckMakeLabel = new javax.swing.JLabel();
        truckMakeField = new javax.swing.JComboBox<>();
        truckModelLabel = new javax.swing.JLabel();
        truckModelField = new javax.swing.JTextField();
        truckVinLabel = new javax.swing.JLabel();
        truckVinField = new javax.swing.JTextField();
        truckYearLabel = new javax.swing.JLabel();
        truckYearField = new javax.swing.JFormattedTextField();

        org.openide.awt.Mnemonics.setLocalizedText(instructionsLabel, org.openide.util.NbBundle.getMessage(TruckPanel.class, "TruckPanel.instructionsLabel.text")); // NOI18N

        truckPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(TruckPanel.class, "TruckPanel.truckPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(truckMakeLabel, org.openide.util.NbBundle.getMessage(TruckPanel.class, "TruckPanel.truckMakeLabel.text")); // NOI18N

        truckMakeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Make...", "Agrale", "Autocar", "Avia", "Ford", "Foton Auman", "Freightliner", "GMC", "Hino", "Hyundai Xcient", "International", "Isuzu", "Iveco", "Kenworth", "KrAZ", "LIAZ", "Mack", "MAN", "Marmon", "MAZ", "Mercedes-Benz", "Mitsubishi Fuso", "Opel", "Oshkosh", "Peterbilt", "Pierce", "Praga", "Reo", "Republic", "Scania", "Skoda", "SNVI", "Sterling", "Tata Prima", "Tatra", "Tesla", "UD Quon", "Volvo", "Western Star", "White" }));

        org.openide.awt.Mnemonics.setLocalizedText(truckModelLabel, org.openide.util.NbBundle.getMessage(TruckPanel.class, "TruckPanel.truckModelLabel.text")); // NOI18N

        truckModelField.setText(org.openide.util.NbBundle.getMessage(TruckPanel.class, "TruckPanel.truckModelField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(truckVinLabel, org.openide.util.NbBundle.getMessage(TruckPanel.class, "TruckPanel.truckVinLabel.text")); // NOI18N

        truckVinField.setText(org.openide.util.NbBundle.getMessage(TruckPanel.class, "TruckPanel.truckVinField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(truckYearLabel, org.openide.util.NbBundle.getMessage(TruckPanel.class, "TruckPanel.truckYearLabel.text")); // NOI18N

        truckYearField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0000"))));
        truckYearField.setText(org.openide.util.NbBundle.getMessage(TruckPanel.class, "TruckPanel.truckYearField.text")); // NOI18N
        truckYearField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                truckYearFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout truckPanelLayout = new javax.swing.GroupLayout(truckPanel);
        truckPanel.setLayout(truckPanelLayout);
        truckPanelLayout.setHorizontalGroup(
            truckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(truckPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(truckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(truckYearLabel)
                    .addComponent(truckVinLabel)
                    .addComponent(truckMakeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(truckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(truckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(truckPanelLayout.createSequentialGroup()
                            .addComponent(truckMakeField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(truckModelLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(truckModelField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(truckVinField))
                    .addComponent(truckYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        truckPanelLayout.setVerticalGroup(
            truckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(truckPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(truckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(truckMakeLabel)
                    .addComponent(truckMakeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(truckModelLabel)
                    .addComponent(truckModelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(truckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(truckVinLabel)
                    .addComponent(truckVinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(truckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(truckYearLabel)
                    .addComponent(truckYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(instructionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(truckPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(truckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void truckYearFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_truckYearFieldFocusLost
        if (truckYearField.getText() != null
                && !truckYearField.getText().isEmpty()) {
            // We are going to attempt to convert the value to an integer.
            try {
                int year = Integer.parseInt(truckYearField.getText());

                // If we get here, then the year parsed successfully, but that
                //+ does not mean that it is valid. We will check that now.
                if (year < 1900) {
                    NotifyUtil.error("Invalid Year", "The provided yer is not a "
                            + "valid year.", true);
                    
                    truckYearField.setBackground(Color.red);
                    truckYearField.requestFocusInWindow();
                } else {
                    truckYearField.setBackground(SystemColor.text);
                }

                Date today = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
                String currentYear = sdf.format(today);
                int curYr = Integer.parseInt(currentYear);

                if (year > curYr) {
                    NotifyUtil.error("Invalid Year", "The provided year ("
                            + year + ") is beyond the current year.\nThis is "
                            + "not possible.", true);
                    
                    truckYearField.setBackground(Color.red);
                    truckYearField.requestFocusInWindow();
                } else {
                    truckYearField.setBackground(SystemColor.text);
                }
                
            } catch (NumberFormatException ex) {
                String msg = "The value (" + truckYearField.getText() + ") is "
                        + "not a valid year.";
                truckYearField.setBackground(Color.red);
                NotifyUtil.error("Number Format Exception", ex.getMessage(), ex,
                        true);
                    
                    truckYearField.requestFocusInWindow();
            }
        }
    }//GEN-LAST:event_truckYearFieldFocusLost

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(TruckPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(TruckPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(TruckPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(TruckPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JComboBox<String> truckMakeField;
    private javax.swing.JLabel truckMakeLabel;
    private javax.swing.JTextField truckModelField;
    private javax.swing.JLabel truckModelLabel;
    private javax.swing.JPanel truckPanel;
    private javax.swing.JTextField truckVinField;
    private javax.swing.JLabel truckVinLabel;
    private javax.swing.JFormattedTextField truckYearField;
    private javax.swing.JLabel truckYearLabel;
    // End of variables declaration//GEN-END:variables
}
